runnum=input('Which run suffix to use? ');

eval(['jetprof',num2str(runnum),'=jetprof;']);
eval(['jetqmse',num2str(runnum),'=jetqmse;']);
eval(['jetqpol',num2str(runnum),'=jetqpol;']);
eval(['jetidn',num2str(runnum),'=jetidn;']);
eval(['jettemp',num2str(runnum),'=jettemp;']);
eval(['jetefit',num2str(runnum),'=jetefit;']);

eval(['save(',char(39),'zjet',num2str(runnum),'data.mat',char(39),',',...
    char(39),'jetprof',num2str(runnum),char(39),',',...
    char(39),'jetqmse',num2str(runnum),char(39),',',...
    char(39),'jetqpol',num2str(runnum),char(39),',',...
    char(39),'jettemp',num2str(runnum),char(39),',',...
    char(39),'jetidn',num2str(runnum),char(39),',',...
    char(39),'jetefit',num2str(runnum),char(39),');']);

    
